apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: email
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
