apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
