apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app: cart
    tier: backend
spec:
  selector:
    app: cart
  ports:
    - name: http
      protocol: TCP
      port: 8883
      targetPort: 8883
  type: ClusterIP
