
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: huajuan6848/email:lab2
        workingDir: /app
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: email-config-volume
          mountPath: /app/conf/dev/conf.yaml
          subPath: conf.yaml
      volumes:
      - name: email-config-volume
        configMap:
          name: email-config
