
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: huajuan6848/user:lab2
        workingDir: /app
        ports:
        - containerPort: 8882
        volumeMounts:
        - name: user-config-volume
          mountPath: /app/conf/dev/conf.yaml
          subPath: conf.yaml
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: user-config-volume
        configMap:
          name: user-config
