apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cart-config
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
data:
  conf.yaml: |
    kitex:
      service: "cart"
      address: ":8883"
      metrics_port: ":9993"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50

    mysql:
      dsn: "%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local"
      username: {{ .Values.externalServices.mysql.username | quote }}
      password: {{ .Values.externalServices.mysql.password | quote }}
      address: {{ .Values.externalServices.mysql.host | quote }}
      port: {{ .Values.externalServices.mysql.port }}
      database: "cart"

    rate_limiter:
      enabled: true
      bucket_size: 10
      rate: 7
