
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-checkout-config
  namespace: default
data:
  conf.yaml: |
    kitex:
      service: "checkout"
      address: ":8884"
      metrics_port: ":9994"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50

    nats:
      url: "nats://{{ .Values.externalServices.nats.host }}:{{ .Values.externalServices.nats.port }}"

    rate_limiter:
      enabled: true
      bucket_size: 10
      rate: 2
