
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  namespace: default
data:
  conf.yaml: |
    hertz:
      address: ":8080"
      metrics_port: 8090
      enable_pprof: false
      enable_gzip: true
      enable_access_log: true
      log_level: info
      log_file_name: "log/hertz.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50
      registry_addr: "localhost:8500"

    redis:
      address: "{{ .Values.externalServices.redis.host }}:{{ .Values.externalServices.redis.port }}"
      username: {{ .Values.externalServices.redis.username | quote }}
      password: {{ .Values.externalServices.redis.password | quote }}
      db: {{ .Values.externalServices.redis.db }}

    session_secret: fudan2025
