
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-user-config
  namespace: default
data:
  conf.yaml: |
    kitex:
      service: "user"
      address: ":8882"
      metrics_port: ":9992"
      log_level: debug
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50

    mysql:
      dsn: "%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local"
      username: {{ .Values.externalServices.mysql.username | quote }}
      password: {{ .Values.externalServices.mysql.password | quote }}
      address: {{ .Values.externalServices.mysql.host | quote }}
      port: {{ .Values.externalServices.mysql.port }}
      database: user

    rate_limiter:
      enabled: false
      bucket_size: 10
      rate: 5
