
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-email
  namespace: default
spec:
  replicas: {{.Values.microservices.replicas}}
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: huajuan6848/email:lab2
        workingDir: /app
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: email-config-volume
          mountPath: /app/conf/dev/conf.yaml
          subPath: conf.yaml
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: email-config-volume
        configMap:
          name: email-config
